/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DefiKicksAdapterRegistry } from "./DefiKicksAdapterRegistry";
export type { DefiKicksDataGovernanceToken } from "./DefiKicksDataGovernanceToken";
export type { ERC20 } from "./ERC20";
export type { GovernorContract } from "./GovernorContract";
export * as factories from "./factories";
export { DefiKicksAdapterRegistry__factory } from "./factories/DefiKicksAdapterRegistry__factory";
export { DefiKicksDataGovernanceToken__factory } from "./factories/DefiKicksDataGovernanceToken__factory";
export { ERC20__factory } from "./factories/ERC20__factory";
export { GovernorContract__factory } from "./factories/GovernorContract__factory";
