/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DefiKicksAdapterRegistry__factory } from "./DefiKicksAdapterRegistry__factory";
export { DefiKicksDataGovernanceToken__factory } from "./DefiKicksDataGovernanceToken__factory";
export { ERC20__factory } from "./ERC20__factory";
export { GovernorContract__factory } from "./GovernorContract__factory";
