/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20Snapshot } from "./ERC20Snapshot";
export type { IERC20Metadata } from "./IERC20Metadata";
